name: base_bloc_v2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_annotation: ^4.8.1
  floor: ^1.4.2
  auto_route: ^7.7.1
  connectivity_plus: ^2.3.0
  get_it: ^7.6.0
  injectable:
  fimber: ^0.6.6
  equatable: ^2.0.3
  http_mock_adapter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: 2.4.5
  json_serializable:
  retrofit_generator:
  injectable_generator:
  floor_generator:
  auto_route_generator: ^7.2.0

flutter:
  uses-material-design: true
